//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSmartAirports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int id { get; set; }
        public string name { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public System.DateTime time { get; set; }
        public string gate { get; set; }
    }
}
