//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSmartAirports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengersInflights
    {
        public int id { get; set; }
        public string pass_id { get; set; }
        public string flight_id { get; set; }
    }
}
