//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsSmartAirports
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int id { get; set; }
        public string shop { get; set; }
        public int id_pass { get; set; }
        public int value { get; set; }
    }
}
